### ISSUE TITLE
Running on OSX

### ISSUE THREAD

**Issue by voidnothings** [gregrs-uk/osm-ov2#1]
Hello, I edited the required lines to change my preferred region and installed osmosis-latest via homebrew. But I can't seem to figure out how to run or install osmconvert.

The script stop around line 30:
`./poi.sh: line 30: osmconvert: command not found`

**Comment by gregrs-uk** [comment]
osm-ov2 depends on [osmconvert](http://wiki.openstreetmap.org/wiki/Osmconvert#Download), which unfortunately doesn't seem to have a Mac version.
